import { z } from "zod";

import {
  JsonValueSchema,
  SchemaVersion,
  buildEnvelopeSchema,
} from "./common.js";

export const BatchItemStatusSchema = z.enum([
  "pending",
  "running",
  "skipped",
  "completed",
  "failed",
]);

export const BatchRunStatusSchema = z.enum([
  "running",
  "completed",
  "failed",
  "incomplete",
]);

export const BatchFailureKindSchema = z.enum([
  "transient",
  "permanent",
  "data_compatibility",
  "local_state_integrity",
  "local_state_lock_timeout",
  "unknown",
]);

export const BatchRecoveryDecisionSchema = z.enum([
  "none",
  "retry_same_run_id",
  "continue_pending",
  "stop_until_fixed",
]);

export const StatusJsonDiagnosticRecoveryDecisionSchema = z.union([
  BatchRecoveryDecisionSchema,
  z.literal("metadata_missing_read_only"),
  z.literal("continue_with_diagnostic_unless_catalog_blocked"),
]);

export const StartupNextOperatorActionSchema = z.enum([
  "run_status_json",
  "run_explicit_repair",
  "run_migrate_only",
  "start_new_run_after_repair",
  "inspect_manual_state",
]);

export const DurableStateDiagnosticSchema = z.object({
  itemId: z.string().min(1).optional(),
  bookId: z.string().min(1).optional(),
  workerId: z.string().min(1).optional(),
  activeCommand: z.string().min(1).optional(),
  failureKind: BatchFailureKindSchema.optional(),
  retryable: z.boolean().optional(),
  localFailureClass: z.string().min(1).optional(),
  recoveryDecision: StatusJsonDiagnosticRecoveryDecisionSchema.optional(),
  failedStage: z.string().min(1).optional(),
  targetLocator: z.string().min(1).optional(),
  redactedEvidenceLocator: z.string().min(1).optional(),
  lane: z.string().min(1).optional(),
  targetMappingOwner: z.string().min(1).optional(),
  laneTimeoutMs: z.number().int().positive().optional(),
  releaseOn: z.array(z.string().min(1)).optional(),
  tempId: z.string().min(1).optional(),
  operationId: z.string().min(1).optional(),
  failedSyscall: z.string().min(1).optional(),
  errno: z.string().min(1).optional(),
  renameCause: z.string().min(1).optional(),
  completedPublishRule: z.string().min(1).optional(),
  lockOwnerEvidence: JsonValueSchema.optional(),
  checksumRecoveryDecision: z.string().min(1).optional(),
  fsyncTarget: z.string().min(1).optional(),
  fsyncErrno: z.string().min(1).optional(),
  fsyncPlatform: z.string().min(1).optional(),
  directoryTargetLocator: z.string().min(1).optional(),
  directoryDurableKind: z.string().min(1).optional(),
  primaryDurableKind: z.string().min(1).optional(),
  durableMode: z.string().min(1).optional(),
  primaryTargetLocator: z.string().min(1).optional(),
  auxiliaryTargetLocator: z.string().min(1).optional(),
  auxiliarySidecarKind: z.string().min(1).optional(),
  sidecarTargetLocator: z.string().min(1).optional(),
  sidecarKind: z.string().min(1).optional(),
  checksumExpected: z.string().min(1).nullable().optional(),
  checksumActual: z.string().min(1).optional(),
  cleanupReason: z.string().min(1).optional(),
  repairAllowed: z.boolean().optional(),
  statusJsonDecision: z.string().min(1).optional(),
  diagnosticClass: z.string().min(1).optional(),
  normalRunnerAction: z.string().min(1).optional(),
  scannedTargetCount: z.number().int().nonnegative().optional(),
  degradedTargetCount: z.number().int().nonnegative().optional(),
  sampleTargetLocators: z.array(z.string().min(1)).optional(),
  scanTruncated: z.boolean().optional(),
  maxRunnerStartScannedTargets: z.number().int().positive().optional(),
  maxRunnerStartReportedSamples: z.number().int().positive().optional(),
  maxRunnerStartMutationCount: z.number().int().nonnegative().optional(),
  repairBoundary: z.string().min(1).optional(),
  repairScope: z.string().min(1).optional(),
  repairTargetFamily: z.string().min(1).optional(),
  maxScannedTargets: z.number().int().positive().optional(),
  maxMutationCount: z.number().int().nonnegative().optional(),
  limitHit: z.boolean().optional(),
  evidenceIncomplete: z.boolean().optional(),
  evidenceIncompleteReason: z.string().min(1).optional(),
  unavailableFieldSentinels: z.array(z.string().min(1)).optional(),
  leaseGeneration: z.number().int().positive().optional(),
  bookLeaseGeneration: z.number().int().positive().optional(),
});

export const StartupRecoverySchema = z.object({
  runId: z.string().min(1).optional(),
  stage: z.string().min(1).optional(),
  scopeCount: z.number().int().nonnegative().optional(),
  targetCount: z.number().int().nonnegative().optional(),
  degradedTargetCount: z.number().int().nonnegative().optional(),
  mutationCount: z.number().int().nonnegative().optional(),
  firstSample: z.string().min(1).optional(),
  lastSample: z.string().min(1).optional(),
  firstBlocker: DurableStateDiagnosticSchema.optional(),
  decision: z.string().min(1).optional(),
  recoveryDecision: BatchRecoveryDecisionSchema.optional(),
  nextOperatorAction: StartupNextOperatorActionSchema.optional(),
  repairBoundary: z.string().min(1).optional(),
  repairScope: z.string().min(1).optional(),
  repairTargetFamily: z.string().min(1).optional(),
  maxScannedTargets: z.number().int().positive().optional(),
  maxMutationCount: z.number().int().nonnegative().optional(),
  limitHit: z.boolean().optional(),
  explicitRepairHint: z.string().min(1).optional(),
  providerRequestDiagnostics: z.array(DurableStateDiagnosticSchema).optional(),
  updatedAt: z.string().datetime().optional(),
}).passthrough();

export const BatchProjectRelativeLocatorSchema = z.string().min(1).refine(
  (value) => {
    if (value.includes("\0")) return false;
    if (value.startsWith("/") || value.startsWith("\\")) return false;
    if (/^[A-Za-z]:[\\/]/u.test(value)) return false;
    if (/^[A-Za-z][A-Za-z0-9+.-]*:/u.test(value)) return false;
    return !value.split(/[\\/]+/u).some((part) => part === "" || part === "..");
  },
  "path must be project-relative and portable",
);
export const BatchLeaseSchema = z.object({
  runnerSessionId: z.string().min(1),
  runnerHost: z.string().min(1),
  runnerPid: z.number().int().positive(),
  generation: z.number().int().positive(),
  fencingToken: z.string().min(1),
  acquiredAt: z.string().datetime(),
  heartbeatAt: z.string().datetime(),
  expiresAt: z.string().datetime(),
});

export const BatchCoordinatorLockSchema = BatchLeaseSchema.extend({
  schemaVersion: z.literal(SchemaVersion),
  runId: z.string().min(1),
  bookConcurrency: z.number().int().positive(),
  openaiProviderConcurrency: z.number().int().positive(),
  jinaProviderConcurrency: z.number().int().positive(),
  localCpuConcurrency: z.number().int().positive(),
});

export const BatchProviderSlotLeaseSchema = BatchLeaseSchema.extend({
  schemaVersion: z.literal(SchemaVersion),
  runId: z.string().min(1),
  provider: z.enum(["openai", "jina", "local_cpu", "qmd_index_writer"]),
  slotId: z.string().min(1),
  itemId: z.string().min(1).optional(),
  bookId: z.string().min(1).optional(),
  workerId: z.string().min(1).optional(),
  command: z.string().min(1).optional(),
  limit: z.number().int().positive(),
  waitMs: z.number().int().nonnegative().optional(),
});

export const BatchBookLeaseSchema = BatchLeaseSchema.extend({
  schemaVersion: z.literal(SchemaVersion),
  runId: z.string().min(1),
  bookId: z.string().min(1),
  itemId: z.string().min(1),
  workerId: z.string().min(1).optional(),
});

export const BatchSubprocessRecordSchema = z.object({
  schemaVersion: z.literal(SchemaVersion),
  runId: z.string().min(1),
  subprocessId: z.string().min(1),
  runnerSessionId: z.string().min(1),
  runnerHost: z.string().min(1),
  runnerPid: z.number().int().positive(),
  pid: z.number().int().positive().optional(),
  command: z.string().min(1),
  itemId: z.string().min(1).optional(),
  bookId: z.string().min(1).optional(),
  workerId: z.string().min(1).optional(),
  providerSlotId: z.string().min(1).optional(),
  providerSlotProvider: z.enum([
    "openai",
    "jina",
    "local_cpu",
    "qmd_index_writer",
  ]).optional(),
  providerSlotGeneration: z.number().int().positive().optional(),
  providerSlotFencingToken: z.string().min(1).optional(),
  processGroup: z.boolean(),
  startedAt: z.string().datetime(),
  heartbeatAt: z.string().datetime(),
  status: z.enum(["running", "exited", "killed", "quarantined", "spawn_error"]),
  exitCode: z.number().int().nullable().optional(),
  signal: z.string().min(1).nullable().optional(),
  completedAt: z.string().datetime().optional(),
});

export const BatchBuildStatusSchema = z.object({
  status: z.enum(["pending", "running", "succeeded", "failed", "stale"]),
  checkedAt: z.string().datetime().optional(),
  stage: z.string().min(1).optional(),
  reason: z.string().min(1).optional(),
  artifactIds: z.array(z.string().min(1)).default([]),
  evidenceLocator: BatchProjectRelativeLocatorSchema.optional(),
  producerRunId: z.string().min(1).optional(),
  bookId: z.string().min(1).optional(),
  sourceHash: z.string().min(1).optional(),
  normalizedContentHash: z.string().min(1).optional(),
});

export const BatchCommandCheckSchema = z.object({
  name: z.string().min(1),
  status: z.enum(["passed", "failed"]),
  attempts: z.number().int().positive(),
  exitCode: z.number().int().nullable(),
  stdoutBytes: z.number().int().nonnegative(),
  stderrBytes: z.number().int().nonnegative(),
  startedAt: z.string().datetime(),
  completedAt: z.string().datetime(),
  nextRetryAt: z.string().datetime().optional(),
  retryDelaySeconds: z.number().int().nonnegative().optional(),
  failureKind: BatchFailureKindSchema.optional(),
  retryable: z.boolean().optional(),
  retryAfterSeconds: z.number().int().nonnegative().optional(),
  attemptExhausted: z.boolean().optional(),
  providerStatusCode: z.number().int().positive().optional(),
  recoveryDecision: BatchRecoveryDecisionSchema.optional(),
  localFailureClass: z.string().min(1).optional(),
  targetLocator: z.string().min(1).optional(),
  redactedEvidenceLocator: z.string().min(1).optional(),
  lane: z.string().min(1).optional(),
  targetMappingOwner: z.string().min(1).optional(),
  laneTimeoutMs: z.number().int().positive().optional(),
  releaseOn: z.array(z.string().min(1)).optional(),
  tempId: z.string().min(1).optional(),
  operationId: z.string().min(1).optional(),
  failedSyscall: z.string().min(1).optional(),
  errno: z.string().min(1).optional(),
  renameCause: z.string().min(1).optional(),
  completedPublishRule: z.string().min(1).optional(),
  lockOwnerEvidence: JsonValueSchema.optional(),
  checksumRecoveryDecision: z.string().min(1).optional(),
  fsyncTarget: z.string().min(1).optional(),
  fsyncErrno: z.string().min(1).optional(),
  fsyncPlatform: z.string().min(1).optional(),
  directoryTargetLocator: z.string().min(1).optional(),
  directoryDurableKind: z.string().min(1).optional(),
  primaryDurableKind: z.string().min(1).optional(),
  durableMode: z.string().min(1).optional(),
  primaryTargetLocator: z.string().min(1).optional(),
  auxiliaryTargetLocator: z.string().min(1).optional(),
  auxiliarySidecarKind: z.string().min(1).optional(),
  sidecarTargetLocator: z.string().min(1).optional(),
  sidecarKind: z.string().min(1).optional(),
  checksumExpected: z.string().min(1).nullable().optional(),
  checksumActual: z.string().min(1).optional(),
  cleanupReason: z.string().min(1).optional(),
  repairAllowed: z.boolean().optional(),
  evidenceIncomplete: z.boolean().optional(),
  evidenceIncompleteReason: z.string().min(1).optional(),
  unavailableFieldSentinels: z.array(z.string().min(1)).optional(),
  runnerSessionId: z.string().min(1).optional(),
  runnerHost: z.string().min(1).optional(),
  runnerPid: z.number().int().positive().optional(),
  workerId: z.string().min(1).optional(),
  itemId: z.string().min(1).optional(),
  bookId: z.string().min(1).optional(),
  ownerPid: z.number().int().positive().optional(),
  ownerHost: z.string().min(1).optional(),
  createdAt: z.string().datetime().optional(),
  expiresAt: z.string().datetime().optional(),
  leaseGeneration: z.number().int().positive().optional(),
  bookLeaseGeneration: z.number().int().positive().optional(),
  targetGeneration: z.number().int().positive().optional(),
  fencingTokenHash: z.string().min(1).optional(),
  failedStage: z.string().min(1).optional(),
  errorSummary: z.string().max(1000).optional(),
});

const BatchItemCheckpointObjectSchema = z.object({
  schemaVersion: z.literal(SchemaVersion),
  itemId: z.string().min(1),
  runId: z.string().min(1),
  status: BatchItemStatusSchema,
  sourceName: z.string().min(1),
  sourceRelativePath: BatchProjectRelativeLocatorSchema,
  sourceIdentityPath: BatchProjectRelativeLocatorSchema,
  sourceHash: z.string().min(1),
  normalizedPath: BatchProjectRelativeLocatorSchema,
  bookId: z.string().min(1),
  attempts: z.number().int().nonnegative(),
  expectedCommandCheckCount: z.number().int().positive().optional(),
  maxCommandAttempts: z.number().int().positive().optional(),
  maxTransientCommandAttempts: z.number().int().positive().optional(),
  maxResumePasses: z.number().int().positive().optional(),
  retryBaseDelaySeconds: z.number().int().positive().optional(),
  retryMaxDelaySeconds: z.number().int().positive().optional(),
  retryBudgetSeconds: z.number().int().positive().optional(),
  maxProviderRecoveryWaits: z.number().int().positive().optional(),
  commandTimeoutSeconds: z.number().int().positive().optional(),
  retryStartedAt: z.string().datetime().optional(),
  runnerSessionId: z.string().min(1).optional(),
  runnerHost: z.string().min(1).optional(),
  runnerPid: z.number().int().positive().optional(),
  runnerHeartbeatAt: z.string().datetime().optional(),
  workerId: z.string().min(1).optional(),
  leaseGeneration: z.number().int().positive().optional(),
  fencingToken: z.string().min(1).optional(),
  leaseExpiresAt: z.string().datetime().optional(),
  bookLeaseGeneration: z.number().int().positive().optional(),
  bookFencingToken: z.string().min(1).optional(),
  orphanedRunnerDetectedAt: z.string().datetime().optional(),
  currentCommand: z.string().min(1).optional(),
  activeCommand: z.string().min(1).optional(),
  currentCommandStartedAt: z.string().datetime().optional(),
  nextRetryAt: z.string().datetime().optional(),
  retryDelaySeconds: z.number().int().nonnegative().optional(),
  failureKind: BatchFailureKindSchema.optional(),
  retryable: z.boolean().optional(),
  retryExhausted: z.boolean().optional(),
  recoveryDecision: BatchRecoveryDecisionSchema.optional(),
  localFailureClass: z.string().min(1).optional(),
  targetLocator: z.string().min(1).optional(),
  redactedEvidenceLocator: z.string().min(1).optional(),
  lane: z.string().min(1).optional(),
  targetMappingOwner: z.string().min(1).optional(),
  laneTimeoutMs: z.number().int().positive().optional(),
  releaseOn: z.array(z.string().min(1)).optional(),
  tempId: z.string().min(1).optional(),
  operationId: z.string().min(1).optional(),
  failedSyscall: z.string().min(1).optional(),
  errno: z.string().min(1).optional(),
  renameCause: z.string().min(1).optional(),
  completedPublishRule: z.string().min(1).optional(),
  lockOwnerEvidence: JsonValueSchema.optional(),
  checksumRecoveryDecision: z.string().min(1).optional(),
  fsyncTarget: z.string().min(1).optional(),
  fsyncErrno: z.string().min(1).optional(),
  fsyncPlatform: z.string().min(1).optional(),
  directoryTargetLocator: z.string().min(1).optional(),
  directoryDurableKind: z.string().min(1).optional(),
  primaryDurableKind: z.string().min(1).optional(),
  durableMode: z.string().min(1).optional(),
  primaryTargetLocator: z.string().min(1).optional(),
  auxiliaryTargetLocator: z.string().min(1).optional(),
  auxiliarySidecarKind: z.string().min(1).optional(),
  sidecarTargetLocator: z.string().min(1).optional(),
  sidecarKind: z.string().min(1).optional(),
  checksumExpected: z.string().min(1).nullable().optional(),
  checksumActual: z.string().min(1).optional(),
  cleanupReason: z.string().min(1).optional(),
  repairAllowed: z.boolean().optional(),
  evidenceIncomplete: z.boolean().optional(),
  evidenceIncompleteReason: z.string().min(1).optional(),
  unavailableFieldSentinels: z.array(z.string().min(1)).optional(),
  ownerPid: z.number().int().positive().optional(),
  ownerHost: z.string().min(1).optional(),
  createdAt: z.string().datetime().optional(),
  expiresAt: z.string().datetime().optional(),
  targetGeneration: z.number().int().positive().optional(),
  fencingTokenHash: z.string().min(1).optional(),
  failedStage: z.string().min(1).optional(),
  qmdBuildStatus: BatchBuildStatusSchema.optional(),
  graphBuildStatus: BatchBuildStatusSchema.optional(),
  graphQueryStatus: BatchBuildStatusSchema.optional(),
  startedAt: z.string().datetime().optional(),
  completedAt: z.string().datetime().optional(),
  failedAt: z.string().datetime().optional(),
  errorSummary: z.string().max(1000).optional(),
  commandChecks: z.array(BatchCommandCheckSchema).default([]),
  metadata: z.record(z.string(), JsonValueSchema).optional(),
});

const BatchItemCheckpointPersistedObjectSchema =
  BatchItemCheckpointObjectSchema.extend({
    qmdBuildStatus: BatchBuildStatusSchema,
    graphBuildStatus: BatchBuildStatusSchema,
    graphQueryStatus: BatchBuildStatusSchema,
  });

export const BatchItemCheckpointSchema =
  BatchItemCheckpointPersistedObjectSchema.superRefine((value, ctx) => {
    if (value.status === "running") {
      for (const field of [
        "runnerSessionId",
        "runnerHost",
        "runnerPid",
        "runnerHeartbeatAt",
        "leaseGeneration",
        "fencingToken",
        "leaseExpiresAt",
        "bookLeaseGeneration",
        "bookFencingToken",
      ] as const) {
        if (value[field] == null) {
          ctx.addIssue({
            code: z.ZodIssueCode.custom,
            message: `running checkpoint requires ${field}`,
            path: [field],
          });
        }
      }
    }
    if (value.retryExhausted === true && (
      value.retryable !== false ||
      value.recoveryDecision !== "stop_until_fixed"
    )) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message:
          "retryExhausted checkpoint requires retryable=false " +
          "and recoveryDecision=stop_until_fixed",
        path: ["retryExhausted"],
      });
    }
  });

export const BatchRunManifestSchema = z.object({
  schemaVersion: z.literal(SchemaVersion),
  runId: z.string().min(1),
  status: BatchRunStatusSchema,
  sourceRootName: z.string().min(1),
  stateRootLocator: BatchProjectRelativeLocatorSchema,
  qmdIndexLocator: BatchProjectRelativeLocatorSchema,
  configLocator: BatchProjectRelativeLocatorSchema,
  totalItems: z.number().int().nonnegative(),
  pendingItems: z.number().int().nonnegative().default(0),
  runningItems: z.number().int().nonnegative().default(0),
  completedItems: z.number().int().nonnegative(),
  skippedItems: z.number().int().nonnegative().default(0),
  importedCompletedItems: z.number().int().nonnegative().default(0),
  failedItems: z.number().int().nonnegative(),
  expectedCommandCheckCount: z.number().int().positive().optional(),
  maxCommandAttempts: z.number().int().positive().optional(),
  maxTransientCommandAttempts: z.number().int().positive().optional(),
  maxResumePasses: z.number().int().positive().optional(),
  retryBaseDelaySeconds: z.number().int().positive().optional(),
  retryMaxDelaySeconds: z.number().int().positive().optional(),
  retryBudgetSeconds: z.number().int().positive().optional(),
  maxProviderRecoveryWaits: z.number().int().positive().optional(),
  commandTimeoutSeconds: z.number().int().positive().optional(),
  heartbeatIntervalSeconds: z.number().int().positive().optional(),
  activeProviderSlots: z.number().int().nonnegative().optional(),
  activeSubprocesses: z.number().int().nonnegative().optional(),
  activeBookLeases: z.number().int().nonnegative().optional(),
  startedAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
  completedAt: z.string().datetime().optional(),
  failedAt: z.string().datetime().optional(),
  itemIds: z.array(z.string().min(1)),
  durableFailureSummary: z.object({
    failureKind: BatchFailureKindSchema.optional(),
    localFailureClass: z.string().min(1).optional(),
    recoveryDecision: BatchRecoveryDecisionSchema.optional(),
    failedStage: z.string().min(1).optional(),
    targetLocator: z.string().min(1).optional(),
    redactedEvidenceLocator: z.string().min(1).optional(),
    lane: z.string().min(1).optional(),
    targetMappingOwner: z.string().min(1).optional(),
    laneTimeoutMs: z.number().int().positive().optional(),
    releaseOn: z.array(z.string().min(1)).optional(),
    tempId: z.string().min(1).optional(),
    operationId: z.string().min(1).optional(),
    failedSyscall: z.string().min(1).optional(),
    errno: z.string().min(1).optional(),
    renameCause: z.string().min(1).optional(),
    completedPublishRule: z.string().min(1).optional(),
    lockOwnerEvidence: JsonValueSchema.optional(),
    checksumRecoveryDecision: z.string().min(1).optional(),
    fsyncTarget: z.string().min(1).optional(),
    fsyncErrno: z.string().min(1).optional(),
    fsyncPlatform: z.string().min(1).optional(),
    directoryTargetLocator: z.string().min(1).optional(),
    directoryDurableKind: z.string().min(1).optional(),
    primaryDurableKind: z.string().min(1).optional(),
    durableMode: z.string().min(1).optional(),
    primaryTargetLocator: z.string().min(1).optional(),
    auxiliaryTargetLocator: z.string().min(1).optional(),
    auxiliarySidecarKind: z.string().min(1).optional(),
    sidecarTargetLocator: z.string().min(1).optional(),
    sidecarKind: z.string().min(1).optional(),
    checksumExpected: z.string().min(1).nullable().optional(),
    checksumActual: z.string().min(1).optional(),
    cleanupReason: z.string().min(1).optional(),
    repairAllowed: z.boolean().optional(),
    evidenceIncomplete: z.boolean().optional(),
    evidenceIncompleteReason: z.string().min(1).optional(),
    unavailableFieldSentinels: z.array(z.string().min(1)).optional(),
  }).optional(),
  metadata: z.record(z.string(), JsonValueSchema).optional(),
});

export const BatchEventLogSchema = z.object({
  schemaVersion: z.literal(SchemaVersion),
  runId: z.string().min(1),
  eventId: z.string().min(1),
  sequence: z.number().int().positive(),
  runnerSessionId: z.string().min(1),
  coordinatorGeneration: z.number().int().positive().optional(),
  itemId: z.string().min(1).optional(),
  event: z.string().min(1),
  status: BatchItemStatusSchema.optional(),
  command: z.string().min(1).optional(),
  failureKind: BatchFailureKindSchema.optional(),
  retryable: z.boolean().optional(),
  retryAfterSeconds: z.number().int().nonnegative().optional(),
  attemptExhausted: z.boolean().optional(),
  providerStatusCode: z.number().int().positive().optional(),
  recoveryDecision: BatchRecoveryDecisionSchema.optional(),
  localFailureClass: z.string().min(1).optional(),
  targetLocator: z.string().min(1).optional(),
  redactedEvidenceLocator: z.string().min(1).optional(),
  lane: z.string().min(1).optional(),
  targetMappingOwner: z.string().min(1).optional(),
  laneTimeoutMs: z.number().int().positive().optional(),
  releaseOn: z.array(z.string().min(1)).optional(),
  tempId: z.string().min(1).optional(),
  operationId: z.string().min(1).optional(),
  failedSyscall: z.string().min(1).optional(),
  errno: z.string().min(1).optional(),
  renameCause: z.string().min(1).optional(),
  completedPublishRule: z.string().min(1).optional(),
  lockOwnerEvidence: JsonValueSchema.optional(),
  checksumRecoveryDecision: z.string().min(1).optional(),
  fsyncTarget: z.string().min(1).optional(),
  fsyncErrno: z.string().min(1).optional(),
  fsyncPlatform: z.string().min(1).optional(),
  directoryTargetLocator: z.string().min(1).optional(),
  directoryDurableKind: z.string().min(1).optional(),
  primaryDurableKind: z.string().min(1).optional(),
  durableMode: z.string().min(1).optional(),
  primaryTargetLocator: z.string().min(1).optional(),
  auxiliaryTargetLocator: z.string().min(1).optional(),
  auxiliarySidecarKind: z.string().min(1).optional(),
  sidecarTargetLocator: z.string().min(1).optional(),
  sidecarKind: z.string().min(1).optional(),
  checksumExpected: z.string().min(1).nullable().optional(),
  checksumActual: z.string().min(1).optional(),
  cleanupReason: z.string().min(1).optional(),
  repairAllowed: z.boolean().optional(),
  evidenceIncomplete: z.boolean().optional(),
  evidenceIncompleteReason: z.string().min(1).optional(),
  unavailableFieldSentinels: z.array(z.string().min(1)).optional(),
  workerId: z.string().min(1).optional(),
  bookId: z.string().min(1).optional(),
  ownerPid: z.number().int().positive().optional(),
  ownerHost: z.string().min(1).optional(),
  createdAt: z.string().datetime().optional(),
  expiresAt: z.string().datetime().optional(),
  leaseGeneration: z.number().int().positive().optional(),
  bookLeaseGeneration: z.number().int().positive().optional(),
  targetGeneration: z.number().int().positive().optional(),
  fencingTokenHash: z.string().min(1).optional(),
  failedStage: z.string().min(1).optional(),
  at: z.string().datetime(),
  message: z.string().max(1000).optional(),
  metadata: z.record(z.string(), JsonValueSchema).optional(),
});

export const BatchRecoverySummaryItemSchema = z.object({
  itemId: z.string().min(1),
  sourceName: z.string().min(1),
  bookId: z.string().min(1),
  status: BatchItemStatusSchema,
  attempts: z.number().int().nonnegative(),
  qmdBuildStatus: BatchBuildStatusSchema,
  commandCheckStatus: BatchBuildStatusSchema.optional(),
  graphBuildStatus: BatchBuildStatusSchema,
  graphQueryStatus: BatchBuildStatusSchema,
  failureKind: BatchFailureKindSchema.optional(),
  retryable: z.boolean().optional(),
  retryExhausted: z.boolean().optional(),
  recoveryDecision: BatchRecoveryDecisionSchema.optional(),
  localFailureClass: z.string().min(1).optional(),
  targetLocator: z.string().min(1).optional(),
  redactedEvidenceLocator: z.string().min(1).optional(),
  lane: z.string().min(1).optional(),
  targetMappingOwner: z.string().min(1).optional(),
  laneTimeoutMs: z.number().int().positive().optional(),
  releaseOn: z.array(z.string().min(1)).optional(),
  tempId: z.string().min(1).optional(),
  operationId: z.string().min(1).optional(),
  failedSyscall: z.string().min(1).optional(),
  errno: z.string().min(1).optional(),
  renameCause: z.string().min(1).optional(),
  completedPublishRule: z.string().min(1).optional(),
  lockOwnerEvidence: JsonValueSchema.optional(),
  checksumRecoveryDecision: z.string().min(1).optional(),
  fsyncTarget: z.string().min(1).optional(),
  fsyncErrno: z.string().min(1).optional(),
  fsyncPlatform: z.string().min(1).optional(),
  directoryTargetLocator: z.string().min(1).optional(),
  directoryDurableKind: z.string().min(1).optional(),
  primaryDurableKind: z.string().min(1).optional(),
  durableMode: z.string().min(1).optional(),
  primaryTargetLocator: z.string().min(1).optional(),
  auxiliaryTargetLocator: z.string().min(1).optional(),
  auxiliarySidecarKind: z.string().min(1).optional(),
  sidecarTargetLocator: z.string().min(1).optional(),
  sidecarKind: z.string().min(1).optional(),
  checksumExpected: z.string().min(1).nullable().optional(),
  checksumActual: z.string().min(1).optional(),
  cleanupReason: z.string().min(1).optional(),
  repairAllowed: z.boolean().optional(),
  evidenceIncomplete: z.boolean().optional(),
  evidenceIncompleteReason: z.string().min(1).optional(),
  unavailableFieldSentinels: z.array(z.string().min(1)).optional(),
  failedStage: z.string().min(1).optional(),
  workerId: z.string().min(1).optional(),
  ownerPid: z.number().int().positive().optional(),
  ownerHost: z.string().min(1).optional(),
  createdAt: z.string().datetime().optional(),
  expiresAt: z.string().datetime().optional(),
  targetGeneration: z.number().int().positive().optional(),
  fencingTokenHash: z.string().min(1).optional(),
  providerStatusCode: z.number().int().positive().optional(),
  retryAfterSeconds: z.number().int().nonnegative().optional(),
  nextRetryAt: z.string().datetime().optional(),
  retryDelaySeconds: z.number().int().nonnegative().optional(),
  retryBudgetSeconds: z.number().int().positive().optional(),
  providerRecoveryWaitCount: z.number().int().nonnegative().optional(),
  maxProviderRecoveryWaits: z.number().int().positive().optional(),
  providerRecoveryReason: z.string().min(1).optional(),
  runnerSessionId: z.string().min(1).optional(),
  runnerHost: z.string().min(1).optional(),
  runnerPid: z.number().int().positive().optional(),
  runnerHeartbeatAt: z.string().datetime().optional(),
  leaseGeneration: z.number().int().positive().optional(),
  fencingToken: z.string().min(1).optional(),
  leaseExpiresAt: z.string().datetime().optional(),
  bookLeaseGeneration: z.number().int().positive().optional(),
  bookFencingToken: z.string().min(1).optional(),
  activeProviderSlots: z.number().int().nonnegative().optional(),
  providerWaitMs: z.number().int().nonnegative().optional(),
  providerSlotGeneration: z.number().int().positive().optional(),
  activeSubprocesses: z.number().int().nonnegative().optional(),
  orphanedRunnerDetectedAt: z.string().datetime().optional(),
  currentCommand: z.string().min(1).optional(),
  activeCommand: z.string().min(1).optional(),
  currentCommandStartedAt: z.string().datetime().optional(),
  waitingForProviderRecovery: z.boolean().optional(),
  reopenedFromStatus: BatchItemStatusSchema.optional(),
  reopenedToStatus: BatchItemStatusSchema.optional(),
  reopenedFromRecoveryDecision: BatchRecoveryDecisionSchema.optional(),
  repairReason: z.string().min(1).optional(),
  repairFailureText: z.string().max(1000).optional(),
  repairedProjection: JsonValueSchema.optional(),
  repairEvidenceLocator: z.string().min(1).optional(),
  reusedProducerRunIds: z.record(z.string(), z.string().min(1)).optional(),
  normalCommandChecksRequired: z.boolean().optional(),
  settingsProjectionDecision: z.enum([
    "already_valid",
    "rewritten",
    "rejected_user_owned",
    "rejected_invalid_source",
  ]).optional(),
  settingsProjectionRewritten: z.boolean().optional(),
  settingsProjectionSourceFingerprint: z.string().min(1).optional(),
  settingsProjectionProjectConfigLocator: z.string().min(1).optional(),
  settingsProjectionLocator: z.string().min(1).optional(),
  settingsProjectionEvidenceLocator: z.string().min(1).optional(),
  settingsProjectionReason: z.string().min(1).optional(),
  localArtifactGateRepairRequiresRealRebuild: z.boolean().optional(),
  localArtifactGateRepairRebuildStage: z.string().min(1).optional(),
  durableChecksumReopenDecision: z.string().min(1).optional(),
  durableChecksumReopenEligible: z.boolean().optional(),
  durableChecksumReopenReason: z.string().min(1).optional(),
  durableChecksumReopenBlockedReason: z.string().min(1).optional(),
  durableChecksumReopenTargetLocator: z.string().min(1).optional(),
  durableChecksumReopenSidecarTargetLocator: z.string().min(1).optional(),
  durableChecksumReopenChecksumMetaLocator: z.string().min(1).optional(),
  durableChecksumReopenChecksum: z.string().min(1).optional(),
  durableChecksumReopenChecksumRecoveryDecision: z.string().min(1).optional(),
  durablePreflightDeferReopenDecision: z.string().min(1).optional(),
  durablePreflightDeferReopenEligible: z.boolean().optional(),
  durablePreflightDeferReopenReason: z.string().min(1).optional(),
  durablePreflightDeferReopenBlockedReason: z.string().min(1).optional(),
  durablePreflightDeferReopenTargetLocator: z.string().min(1).optional(),
  durablePreflightDeferReopenOperationId: z.string().min(1).optional(),
  durablePreflightDeferReopenRunnerSessionId:
    z.string().min(1).optional(),
  providerAuthReopenDecision: z.string().min(1).optional(),
  providerAuthReopenEligible: z.boolean().optional(),
  providerAuthReopenReason: z.string().min(1).optional(),
  providerAuthReopenBlockedReason: z.string().min(1).optional(),
  providerAuthConfigChanged: z.boolean().optional(),
  providerAuthFailureFingerprint: z.string().min(1).optional(),
  currentProviderAuthFingerprint: z.string().min(1).optional(),
  lastProviderAuthReopenFingerprint: z.string().min(1).optional(),
  providerAuthConfigReadStatus: z.string().min(1).optional(),
  providerAuthConfigReadError: z.string().min(1).optional(),
  providerAuthRequiredKeys: z.array(z.string().min(1)).optional(),
  providerAuthRequiredEndpoints: z.array(z.string().min(1)).optional(),
  providerAuthRequiredNames: z.array(z.string().min(1)).optional(),
  providerAuthKeyPresence: z.record(z.string(), z.string().min(1)).optional(),
  providerAuthCredentialSources: z.record(z.string(), z.string().min(1)).optional(),
  providerAuthReadinessStatus: z.string().min(1).optional(),
  providerAuthMissingRequiredKeys: z.array(z.string().min(1)).optional(),
  providerAuthShadowedEnvNames: z.array(z.string().min(1)).optional(),
  providerAuthDotenvShadowedEnvNames: z.array(z.string().min(1)).optional(),
  providerAuthRootDotenvFingerprints:
    z.record(z.string(), z.string().min(1)).optional(),
  providerAuthGraphVaultDotenvFingerprints:
    z.record(z.string(), z.string().min(1)).optional(),
  providerAuthRootDotenvPresent: z.boolean().optional(),
  providerAuthGraphVaultDotenvPresent: z.boolean().optional(),
  providerAuthReopenAttemptCount: z.number().int().nonnegative().optional(),
  legacyProviderAuthFingerprintMissing: z.boolean().optional(),
  errorSummary: z.string().max(1000).optional(),
});

export const BatchRecoverySummarySchema = z.object({
  schemaVersion: z.literal(SchemaVersion),
  runId: z.string().min(1),
  generatedAt: z.string().datetime(),
  manifest: z.object({
    status: BatchRunStatusSchema,
    totalItems: z.number().int().nonnegative(),
    pendingItems: z.number().int().nonnegative(),
    runningItems: z.number().int().nonnegative(),
    completedItems: z.number().int().nonnegative(),
    skippedItems: z.number().int().nonnegative(),
    failedItems: z.number().int().nonnegative(),
    activeProviderSlots: z.number().int().nonnegative().optional(),
    activeSubprocesses: z.number().int().nonnegative().optional(),
    activeBookLeases: z.number().int().nonnegative().optional(),
    updatedAt: z.string().datetime(),
    completedAt: z.string().datetime().optional(),
    failedAt: z.string().datetime().optional(),
  }),
  counts: z.record(z.string(), z.number().int().nonnegative()),
  retryPolicy: z.object({
    maxCommandAttempts: z.number().int().positive(),
    maxTransientCommandAttempts: z.number().int().positive(),
    maxResumePasses: z.number().int().positive(),
    retryBaseDelaySeconds: z.number().int().positive(),
    retryMaxDelaySeconds: z.number().int().positive(),
    retryBudgetSeconds: z.number().int().positive(),
    maxProviderRecoveryWaits: z.number().int().positive(),
    commandTimeoutSeconds: z.number().int().positive(),
    heartbeatIntervalSeconds: z.number().int().positive().optional(),
  }),
  recoveryDecision: BatchRecoveryDecisionSchema,
  retryableItemCount: z.number().int().nonnegative(),
  nextRetryAt: z.string().datetime().optional(),
  durableStateFailures: z.array(DurableStateDiagnosticSchema).optional(),
  durableTempDiagnostics: z.array(DurableStateDiagnosticSchema).optional(),
  durableLockDiagnostics: z.array(DurableStateDiagnosticSchema).optional(),
  startupRecovery: StartupRecoverySchema.optional(),
  items: z.array(BatchRecoverySummaryItemSchema),
});

export const BatchItemCheckpointInputSchema = BatchItemCheckpointObjectSchema.extend({
  sourceIdentityPath: BatchProjectRelativeLocatorSchema.optional(),
  sourceHash: z.string().min(1).optional(),
  bookId: z.string().min(1).optional(),
});

export function parseBatchItemCheckpoint(
  value: unknown,
  defaults: { sourceHash: string; bookId: string; sourceIdentityPath: string },
) {
  const parsed = BatchItemCheckpointInputSchema.parse(value);
  return BatchItemCheckpointSchema.parse({
    ...parsed,
    sourceIdentityPath: parsed.sourceIdentityPath ?? defaults.sourceIdentityPath,
    sourceHash: parsed.sourceHash ?? defaults.sourceHash,
    bookId: parsed.bookId ?? defaults.bookId,
    qmdBuildStatus: parsed.qmdBuildStatus ?? { status: "pending" },
    graphBuildStatus: parsed.graphBuildStatus ?? { status: "pending" },
    graphQueryStatus: parsed.graphQueryStatus ?? { status: "pending" },
  });
}

export const BatchRunManifestEnvelopeSchema = buildEnvelopeSchema(
  "qmd.batch_run.manifest",
  BatchRunManifestSchema,
);

export const BatchItemCheckpointEnvelopeSchema = buildEnvelopeSchema(
  "qmd.batch_run.item_checkpoint",
  BatchItemCheckpointSchema,
);

export const BatchEventLogEnvelopeSchema = buildEnvelopeSchema(
  "qmd.batch_run.event_log",
  BatchEventLogSchema,
);

export const BatchRecoverySummaryEnvelopeSchema = buildEnvelopeSchema(
  "qmd.batch_run.recovery_summary",
  BatchRecoverySummarySchema,
);

export type BatchItemStatus = z.infer<typeof BatchItemStatusSchema>;
export type BatchRunStatus = z.infer<typeof BatchRunStatusSchema>;
export type BatchFailureKind = z.infer<typeof BatchFailureKindSchema>;
export type BatchRecoveryDecision = z.infer<typeof BatchRecoveryDecisionSchema>;
export type BatchBuildStatus = z.infer<typeof BatchBuildStatusSchema>;
export type BatchProjectRelativeLocator = z.infer<
  typeof BatchProjectRelativeLocatorSchema
>;
export type BatchLease = z.infer<typeof BatchLeaseSchema>;
export type BatchCoordinatorLock = z.infer<typeof BatchCoordinatorLockSchema>;
export type BatchProviderSlotLease = z.infer<typeof BatchProviderSlotLeaseSchema>;
export type BatchBookLease = z.infer<typeof BatchBookLeaseSchema>;
export type BatchSubprocessRecord = z.infer<typeof BatchSubprocessRecordSchema>;
export type BatchCommandCheck = z.infer<typeof BatchCommandCheckSchema>;
export type BatchItemCheckpointInput = z.infer<typeof BatchItemCheckpointInputSchema>;
export type BatchItemCheckpoint = z.infer<typeof BatchItemCheckpointSchema>;
export type BatchRunManifest = z.infer<typeof BatchRunManifestSchema>;
export type BatchEventLog = z.infer<typeof BatchEventLogSchema>;
export type BatchRecoverySummaryItem = z.infer<
  typeof BatchRecoverySummaryItemSchema
>;
export type BatchRecoverySummary = z.infer<typeof BatchRecoverySummarySchema>;
